
version: '2'

services:
  angular-pwa-seed:
    image: angular-pwa-seed
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/usr/src/app
    ## set your startup file here
    command: npm run start
